package com.itranswarp.learnjava.service;

import jakarta.annotation.PostConstruct;
import org.hsqldb.server.ServerAcl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataAccessException;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Component;
import org.hsqldb.Server;
import org.hsqldb.persist.HsqlProperties;

import java.io.IOException;

@Component
public class DatabaseInitializer {
  @Autowired
  NamedParameterJdbcTemplate namedParameterJdbcTemplate;

  public static void startDB() throws ServerAcl.AclFormatException, IOException {

    Server hsqlServer = new Server();

    // 配置数据库的属性
    HsqlProperties properties = new HsqlProperties();
    properties.setProperty("server.database.0", "mem:testdb");  // 选择内存数据库
    properties.setProperty("server.dbname.0", "testdb");       // 数据库名称

    // 设置 HSQLDB 配置
    hsqlServer.setProperties(properties);

    // 启动服务器
    hsqlServer.start();

    System.out.println("HSQLDB 服务器已启动，连接地址为 jdbc:hsqldb:hsql://localhost:9001/testdb");
  }

  @PostConstruct
  public void init() {
    String sql = "CREATE TABLE IF NOT EXISTS users ("
        + " id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
        + "email VARCHAR(255) NOT NULL UNIQUE, "
        + "password VARCHAR(255) NOT NULL, "
        + "name VARCHAR(255) NOT NULL"
        + ");";

    // 执行 SQL 语句
    try {
      namedParameterJdbcTemplate.getJdbcTemplate().execute(sql);
    } catch (DataAccessException e) {
      throw new RuntimeException(e);
    }
  }
}
